# Generated by Django 4.1.5 on 2023-01-31 22:25

from django.db import migrations, models
import django.db.models.deletion
import dynamic_filenames
import stdimage.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Competition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='GameStage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('gamestage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.gamestage')),
            ],
        ),
        migrations.CreateModel(
            name='Match',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('matchno', models.IntegerField()),
                ('datetime', models.DateTimeField(blank=True, null=True)),
                ('summarytext', models.TextField(blank=True, null=True)),
                ('summaryphoto', models.ImageField(blank=True, null=True, upload_to='match_summaries')),
            ],
            options={
                'verbose_name_plural': 'Matches',
            },
        ),
        migrations.CreateModel(
            name='MatchEventType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='MatchStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=11)),
            ],
            options={
                'verbose_name_plural': 'Match statuses',
            },
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('short', models.CharField(max_length=255)),
                ('doc', models.CharField(blank=True, max_length=15, null=True)),
                ('dob', models.DateField(blank=True, null=True)),
                ('email', models.EmailField(blank=True, max_length=255, null=True)),
                ('phone1', models.CharField(blank=True, max_length=25, null=True)),
                ('phone2', models.CharField(blank=True, max_length=25, null=True)),
                ('address', models.CharField(blank=True, max_length=255, null=True)),
                ('bankdata', models.TextField(blank=True, null=True)),
                ('photo', stdimage.models.StdImageField(blank=True, force_min_size=False, null=True, upload_to=dynamic_filenames.FilePattern(filename_pattern='person-photos/{uuid:base32}{ext}'), variations={'large': (1200, 800, True), 'medium': (600, 400, True), 'thumb': (300, 200, True)})),
            ],
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Season',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('short', models.CharField(max_length=4)),
                ('description', models.TextField(blank=True, null=True)),
                ('logo', stdimage.models.StdImageField(blank=True, force_min_size=False, null=True, upload_to=dynamic_filenames.FilePattern(filename_pattern='team-logos/{uuid:base32}{ext}'), variations={'small': (70, 70), 'standard': (300, 300), 'thumb': (46, 46)})),
                ('photo', stdimage.models.StdImageField(blank=True, force_min_size=False, null=True, upload_to=dynamic_filenames.FilePattern(filename_pattern='team-photos/{uuid:base32}{ext}'), variations={'large': (1200, 800, True), 'medium': (600, 400, True), 'thumb': (300, 200, True)})),
                ('website', models.URLField(blank=True, max_length=255, null=True)),
                ('facebook', models.URLField(blank=True, max_length=255, null=True)),
                ('istagram', models.URLField(blank=True, max_length=255, null=True)),
                ('twitter', models.URLField(blank=True, max_length=255, null=True)),
                ('youtube', models.URLField(blank=True, max_length=255, null=True)),
                ('admin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.person')),
                ('genre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.genre')),
            ],
        ),
        migrations.CreateModel(
            name='Venue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('address', models.CharField(blank=True, max_length=255, null=True)),
                ('website', models.URLField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Tournament',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('competition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.competition')),
                ('genre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.genre')),
                ('season', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.season')),
            ],
        ),
        migrations.CreateModel(
            name='TeamTournamentRegistration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', stdimage.models.StdImageField(blank=True, force_min_size=False, null=True, upload_to=dynamic_filenames.FilePattern(filename_pattern='team-photos/{uuid:base32}{ext}'), variations={'large': (1200, 800, True), 'medium': (600, 400, True), 'thumb': (300, 200, True)})),
                ('capitain', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.person')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.team')),
                ('tournament', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.tournament')),
            ],
        ),
        migrations.CreateModel(
            name='PlayerTournamentRegistration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.CharField(blank=True, max_length=20, null=True)),
                ('shirtno', models.CharField(max_length=10)),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.person')),
                ('teamreg', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.teamtournamentregistration')),
            ],
        ),
        migrations.AddField(
            model_name='person',
            name='roles',
            field=models.ManyToManyField(to='core.role'),
        ),
        migrations.CreateModel(
            name='MatchEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(blank=True, null=True)),
                ('matchtimeminutes', models.FloatField(blank=True, null=True)),
                ('eventtype', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.matcheventtype')),
                ('match', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.match')),
                ('playerreg', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.playertournamentregistration')),
                ('teamreg', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.teamtournamentregistration')),
            ],
        ),
        migrations.AddField(
            model_name='match',
            name='awayteamreg',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='awayteamreg', to='core.teamtournamentregistration'),
        ),
        migrations.AddField(
            model_name='match',
            name='group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.group'),
        ),
        migrations.AddField(
            model_name='match',
            name='hometeamreg',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hometeamreg', to='core.teamtournamentregistration'),
        ),
        migrations.AddField(
            model_name='match',
            name='matchofficial',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='matchofficial', to='core.person'),
        ),
        migrations.AddField(
            model_name='match',
            name='refree',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='refree', to='core.person'),
        ),
        migrations.AddField(
            model_name='match',
            name='status',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='core.matchstatus'),
        ),
        migrations.AddField(
            model_name='match',
            name='venue',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.venue'),
        ),
        migrations.AddField(
            model_name='group',
            name='teams',
            field=models.ManyToManyField(to='core.teamtournamentregistration'),
        ),
        migrations.AddField(
            model_name='group',
            name='tournament',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.tournament'),
        ),
    ]
