# Generated by Django 4.1.5 on 2023-12-28 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_person_facebook_person_hood_person_instagram_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='actualfinish',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='match',
            name='actualstart',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
