# Generated by Django 4.1.5 on 2023-12-29 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_match_actualfinish_match_actualstart'),
    ]

    operations = [
        migrations.AddField(
            model_name='tournament',
            name='short',
            field=models.CharField(default='short', max_length=255),
            preserve_default=False,
        ),
    ]
