# Generated by Django 4.1.5 on 2023-12-30 22:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_tournament_short'),
    ]

    operations = [
        migrations.AddField(
            model_name='matcheventtype',
            name='name_ptbr',
            field=models.CharField(default='a', max_length=255),
            preserve_default=False,
        ),
    ]
